# Crée une base de données et un utilisateur avec des droits personnalisés
- name: Créer une base et un utilisateur avec droits personnalisés
  hosts: mysql          # Cible les hôtes du groupe 'mysql' /etc/ansible/host
  become: yes           # Exécute les tâches avec les privilèges sudo

  # Demande les informations nécessaires à l'utilisateur
  vars_prompt:
    - name: db_name
      prompt: "Nom de la base à créer"              # Saisir le nom de la base
      private: no

    - name: db_user
      prompt: "Nom de l'utilisateur à créer"        # Saisir le nom de l'utilisateur
      private: no

    - name: db_host
      prompt: "Hôte autorisé pour l'utilisateur"    # Saisir l'adresse IP autorisée (ou % pour tous)
      private: no
      default: "127.0.0.1"                          # Par défaut, l'accès est local seulement

    - name: db_privileges
      prompt: |
        Droits à accorder (séparés par des virgules)
        Exemples : SELECT,INSERT,UPDATE,DELETE      # Saisir les droits à accorder
      private: no
      default: "SELECT"                             # Par défaut, seul le droit SELECT est donné

  # Variables internes
  vars:
    db_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
    # Génère automatiquement un mot de passe sécurisé pour l'utilisateur

    mysql_root_user: arman                          # Utilisateur root MySQL
    mysql_root_password: arman                      # Mot de passe root

  tasks:
    # Crée la base de données
    - name: Créer la base de données
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    # Crée l'utilisateur avec le mot de passe généré
    - name: Créer l'utilisateur avec mot de passe
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "{{ db_host }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    # Attribue les droits spécifiés à l'utilisateur sur la base
    - name: Attribuer les droits personnalisés à l'utilisateur
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        host: "{{ db_host }}"
        priv: "{{ db_name }}.*:{{ db_privileges }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    # Affiche un récapitulatif dans le terminal
    - name: Afficher les informations finales
      debug:
        msg:
          - "Base et utilisateur configurés :"
          - "Base        : {{ db_name }}"
          - "Utilisateur : {{ db_user }}"
          - "Hôte        : {{ db_host }}"
          - "Mot de passe: {{ db_password }}"
          - "Droits      : {{ db_privileges }} sur {{ db_name }}"
