# Créer un utilisateur MariaDB avec mot de passe généré automatiquement
- name: Créer un utilisateur MariaDB
  hosts: mysql                 # Cible les hôtes du groupe 'mysql' /etc/ansible/hosts
  become: true                # Exécute les tâches avec les privilèges sudo

  vars_files:
    - group_vars/all.yml      # Charge les identifiants root depuis un fichier externe

  vars_prompt:
    - name: db_user
      prompt: "Nom de l'utilisateur MariaDB"         # Nom de l'utilisateur à créer
      private: no

    - name: db_host
      prompt: "Hôte autorisé (IP ou % pour tous)"    # IP ou % pour tous les hôtes
      private: no
      default: "127.0.0.1"                            # Par défaut : accès local seulement

  vars:
    # Génère un mot de passe sécurisé (lettres et chiffres)
    db_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"

  tasks:
    # Crée l'utilisateur sans privilèges
    - name: Créer un utilisateur sans privilèges
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "{{ db_host }}"
        state: present
        login_user: "{{ mysql_root_user }}"
        login_password: "{{ mysql_root_password }}"

    # Affiche un récapitulatif
    - name: Afficher les infos utilisateur
      debug:
        msg:
          - "Utilisateur créé avec succès !"
          - "Nom           : {{ db_user }}"
          - "Mot de passe  : {{ db_password }}"
          - "Hôte autorisé : {{ db_host }}"
